name: Create Artifact

on:
  push:
    tags:
      - 'rc-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Resolve dependencies
      run: ./back-end/mvnw -f back-end/pom.xml dependency:resolve 

    - name: Build with Maven
      run: ./back-end/mvnw -f back-end/pom.xml clean install

    - name: Run unit tests
      run: ./back-end/mvnw -f back-end/pom.xml test

    - name: Static Code Analysis
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        ESLINT_CONFIG_FILE: ./.eslintrc.json # Especifique o caminho para o seu arquivo de configuração
        CHECKSTYLE_CONFIG_FILE: ./.checkstyle.xml

    - name: Package the System
      run: |
        version=$(echo ${GITHUB_REF##*/})
        zip -r ${version}.zip back-end/target/

    - name: Upload the package
      uses: actions/upload-artifact@v2
      with:
        name: rc-package
        path: ${{ github.workspace }}/rc-*.zip